### PR TITLE
Semistandard

### PR DESCRIPTION
**Pull request by smashwilson**
I don't have terribly strong opinions about JavaScript style conventions, but having been spoiled by `go fmt`, I _do_ much prefer having something that can be enforced as automatically as possible, and I want something that's consistent across all of our node repositories. To that end I'd like to adopt [semistandard](https://github.com/Flet/semistandard).

I've been using @rgbkrk's [gag fork](https://github.com/rgbkrk/obama) in the content service and it's been fine so far. I like that it's basically drop-in-and-run with no configuration to fiddle with.

@ktbartholomew, any objections or strong opinions here?

### CODE REVIEW

**Comment by rgbkrk** [comment]
Excuse me?!? Obama is totally a production ready fork.

**Comment by ktbartholomew** [comment]
1. I'm a 4-space guy, but can be swayed.
2. I really _like_ JSHint because the style rules are defined in the source, instead of in a module that somebody else controls and is prone to change.
3. I really _don't like_ things that modify my code for me. Most of these changes look pretty safe, and it makes sense to use the formatter as a one-time fix, but I'd rather have a formatter that behaves like a test, where a Travis build would fail if styles weren't being met.

**Comment by ktbartholomew** [comment]
All in all though, the semistandard styles LGTM. We can fuss with execution details later. :shipit:

**Comment by smashwilson** [comment]
> We can fuss with execution details later.

That's pretty much where I'm at :grin: This at least makes everything consistent.

> I really don't like things that modify my code for me. Most of these changes look pretty safe, and it makes sense to use the formatter as a one-time fix, but I'd rather have a formatter that behaves like a test, where a Travis build would fail if styles weren't being met.

Already in place! I touched up our dev dependencies and added a clean `semistandard` pass to `npm test`. You _can_ use `npm run format` if you'd like but I didn't add it anywhere automated. I have an Atom linter for editing needs, too (and I know there's a Sublime one too).

**Comment by smashwilson** [comment]
By the way, we're actually still using jshint too, but I wanted something else because:
- It mostly lints for correctness, but not for style.
- It didn't ship with a tool that could mass-convert existing source easily.

I think [eslint](http://eslint.org/) might be more in line with what we're looking for ultimately, but this was just something I was poking at while waiting for Docker containers to build, so I didn't want to spend a lot of time trying to figure out what my opinions were :stuck_out_tongue:

**Pull request merged**
